name = "ScoreMatchingVI"
uuid = "057f4c57-2f96-425e-b7c3-642f4ea84ccf"
authors = ["Paul Tiede <ptiede91@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
